# Generated by Django 3.0.2 on 2020-01-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='etykieta',
        ),
    ]
