# Generated by Django 3.0.2 on 2020-01-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='promocyjnacena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
