# Generated by Django 3.0.2 on 2020-01-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0003_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='adres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Witryna.Adres'),
        ),
    ]
