# Generated by Django 3.0.2 on 2020-01-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0003_auto_20200115_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='zaplacono',
            field=models.BooleanField(default=False),
        ),
    ]
