# Generated by Django 3.0.2 on 2020-01-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0004_zamowienie_zaplacono'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='rodzaj_platnosci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
