# Generated by Django 3.0.2 on 2020-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0004_zamowienie_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='zapamietano',
            field=models.BooleanField(default=False),
        ),
    ]
