# Generated by Django 3.0.2 on 2020-01-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0005_zamowienie_rodzaj_platnosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='id_zamowienia',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey><django.db.models.fields.DateTimeField>', max_length=100),
        ),
    ]
