# Generated by Django 3.0.2 on 2020-01-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0005_adres_zapamietano'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='imie',
            field=models.CharField(default='Jan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adres',
            name='nazwisko',
            field=models.CharField(default='kowalski', max_length=100),
            preserve_default=False,
        ),
    ]
