# Generated by Django 3.0.2 on 2020-01-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0006_zamowienie_id_zamowienia'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontoBankowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaodbiorcy', models.CharField(max_length=100)),
                ('nrachunku', models.CharField(max_length=100)),
                ('tytul_przelewu', models.CharField(max_length=100)),
            ],
        ),
    ]
