# Generated by Django 3.0.2 on 2020-01-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0007_kontobankowe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontobankowe',
            old_name='nazwaodbiorcy',
            new_name='nazwao_dbiorcy',
        ),
        migrations.RenameField(
            model_name='kontobankowe',
            old_name='nrachunku',
            new_name='nr_achunku',
        ),
        migrations.RemoveField(
            model_name='kontobankowe',
            name='tytul_przelewu',
        ),
    ]
