# Generated by Django 3.0.2 on 2020-01-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Witryna', '0008_auto_20200117_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontobankowe',
            old_name='nr_achunku',
            new_name='nr_rachunku',
        ),
    ]
